FUNCTION(AddHDir PATHLIST)
    LIST(LENGTH ARGV argc)
    SET(i 0)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        INCLUDE_DIRECTORIES(${argvalue})
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
ENDFUNCTION(AddHDir)

FUNCTION(AddHDirWin32 PATHLIST)
IF(WIN32)
    LIST(LENGTH ARGV argc)
    SET(i 0)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        INCLUDE_DIRECTORIES(${argvalue})
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
ENDIF()
ENDFUNCTION(AddHDirWin32)

FUNCTION(AddHDirLinux PATHLIST)
IF(UNIX AND NOT APPLE)
    LIST(LENGTH ARGV argc)
    SET(i 0)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        INCLUDE_DIRECTORIES(${argvalue})
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
ENDIF()
ENDFUNCTION(AddHDirLinux)

FUNCTION(AddHDirOsx PATHLIST)
IF(APPLE)
    LIST(LENGTH ARGV argc)
    SET(i 0)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        INCLUDE_DIRECTORIES(${argvalue})
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
ENDIF()
ENDFUNCTION(AddHDirOsx)

FUNCTION(AddHDirAndroid PATHLIST)
IF(UNIX AND NOT APPLE AND NOT CYGWIN)
    LIST(LENGTH ARGV argc)
    SET(i 0)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        INCLUDE_DIRECTORIES(${argvalue})
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
ENDIF()
ENDFUNCTION(AddHDirAndroid)
